### PR TITLE
Defer initialization until Rails.root is available

### PR DESCRIPTION
**Pull request by kakra**

### CODE REVIEW

**Comment by kakra** [comment]
@halfbyte Did you get this running somehow? When I try, the models aren't avaiable when aaf.rb runs to define the index...

**Comment by halfbyte** [comment]
@kakra Honesty no. I bit the bullet and ported the whole site to another search index.

**Comment by kakra** [comment]
Apparently, no other search indexer seems to support German stemming and a method similar to "more_like_this" at a level that ferret does support, which I heavily rely on. Which alternative did you find? I'd like to have a look if it could support my use cases. ActsAsFerret is currently unusable with Rails 4. We are seeing deadlocks, application freezes, timeouts, etc.

**Comment by kakra** [comment]
Applied only 7094a4e which works.

**Pull request closed without merging**
